<a href="https://colab.research.google.com/github/YashSharma10/AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [25]:
b = np.array([1.1,2.4,3,4])
print(b)

[1.1 2.4 3.  4. ]


In [14]:
c = a + b
print(c)

[2.2 4.8 6.  8. ]


In [22]:
c.sort()
print(c)

[2.2 4.8 6.  8. ]


In [28]:
d = np.array([(1,2,3) , (4,5,6)])
print(d)

[[1 2 3]
 [4 5 6]]


In [29]:
e = np.array([(12,34,55) , (41,25,46)])
print(e)

[[12 34 55]
 [41 25 46]]


In [31]:
f = d + e
print(f)

[[13 36 58]
 [45 30 52]]


In [33]:
g = np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
h = np.arange(10,25,5)
print(h)

[10 15 20]


In [35]:
i = np.linspace(0,2,9)
print(i)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [36]:
j = np.full((2,2),7)
print(j)

[[7 7]
 [7 7]]


In [37]:
k = np.eye(2) # identity matrix
print(k)

[[1. 0.]
 [0. 1.]]


In [39]:
l = np.random.random((2,2))
print(l)

[[0.29162595 0.59471315]
 [0.66652279 0.61651581]]
