<a href="https://colab.research.google.com/github/YashSharma10/AIML/blob/main/Yash_22csu295.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b = np.array([1.1,2.4,3,4])
print(b)

[1.1 2.4 3.  4. ]


In [ ]:
c = a + b
print(c)

[2.2 4.8 6.  8. ]


In [ ]:
c.sort()
print(c)

[2.2 4.8 6.  8. ]


In [ ]:
d = np.array([(1,2,3) , (4,5,6)])
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
e = np.array([(12,34,55) , (41,25,46)])
print(e)

[[12 34 55]
 [41 25 46]]


In [ ]:
f = d + e
print(f)

[[13 36 58]
 [45 30 52]]


In [ ]:
g = np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
h = np.arange(10,25,5)
print(h)

[10 15 20]


In [ ]:
i = np.linspace(0,2,9)
print(i)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
j = np.full((2,2),7)
print(j)

[[7 7]
 [7 7]]


In [ ]:
k = np.eye(2) # identity matrix
print(k)

[[1. 0.]
 [0. 1.]]


In [ ]:
l = np.random.random((2,2))
print(l)

[[0.29162595 0.59471315]
 [0.66652279 0.61651581]]


# EDA Cars


In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

# Importing the dataset
df=pd.read_excel('EDA Cars-1.xlsx')
df.head()

INDEX        INCOME MARITAL STATUS SEX    EDUCATION          JOB  \
0      1  125301.24250             No   F    Bachelors  Blue Collar   
1      2   50815.44531             No   M  High School          NaN   
2      3   62977.82416            NaN   F    Bachelors     Clerical   
3      4   77099.96624             No   F          NaN       Lawyer   
4      5  130794.57420             No   M  High School          NaN   

   TRAVEL TIME         USE  MILES CLOCKED     CAR TYPE  CAR AGE   CITY  \
0    45.703013  Commercial        17430.0   Sports Car      7.0  Texas   
1    20.591628     Private        18930.0      Minivan      1.0  Texas   
2    33.639949     Private            NaN          SUV      1.0  Texas   
3    15.415676         NaN        18300.0   Sports Car     11.0  Texas   
4          NaN  Commercial        28340.0  Panel Truck     10.0  Texas   

   POSTAL CODE  
0      42420.0  
1      42420.0  
2      42420.0  
3      42420.0  
4      42420.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   INDEX           303 non-null    int64  
 1   INCOME          260 non-null    float64
 2   MARITAL STATUS  275 non-null    object 
 3   SEX             297 non-null    object 
 4   EDUCATION       259 non-null    object 
 5   JOB             257 non-null    object 
 6   TRAVEL TIME     262 non-null    float64
 7   USE             250 non-null    object 
 8   MILES CLOCKED   278 non-null    float64
 9   CAR TYPE        293 non-null    object 
 10  CAR AGE         283 non-null    float64
 11  CITY            297 non-null    object 
 12  POSTAL CODE     300 non-null    float64
dtypes: float64(5), int64(1), object(7)
memory usage: 30.9+ KB


In [6]:
df["POSTAL CODE"]=pd.Categorical(df['POSTAL CODE'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype   
---  ------          --------------  -----   
 0   INDEX           303 non-null    int64   
 1   INCOME          260 non-null    float64 
 2   MARITAL STATUS  275 non-null    object  
 3   SEX             297 non-null    object  
 4   EDUCATION       259 non-null    object  
 5   JOB             257 non-null    object  
 6   TRAVEL TIME     262 non-null    float64 
 7   USE             250 non-null    object  
 8   MILES CLOCKED   278 non-null    float64 
 9   CAR TYPE        293 non-null    object  
 10  CAR AGE         283 non-null    float64 
 11  CITY            297 non-null    object  
 12  POSTAL CODE     300 non-null    category
dtypes: category(1), float64(4), int64(1), object(7)
memory usage: 29.2+ KB


In [7]:
dups=df.duplicated()
print('Number of duplicate rows = %d' % (dups.sum()))

Number of duplicate rows = 14
